
// food items
const items = [
  {
    name: "Rice",
    category: "grains",
    price: 9.97,
    weight: 8,
    Color: "#F6F2C5",
    C02: 15,
    Calories: 4.71,
    imgurl: "./img/Grain/rice.png",
  },
  {
    name: "Cabbage",
    category: "vegetables",
    price: 3.0,
    Weight: 10,
    Color: "#3D4935",
    C02: 10,
    Calories: 5,
    imgurl: "./img/Vegetables/cabbage.png",
  },
  {
    name: "Organic Quinoa",
    category: "grains",
    price: 8.99,
    Weight: 2,
    Color: "#F5DEB3",
    C02: 2,
    Calories: 120,
    imgurl: "./img/Grain/Organic Quinoa.png",
  },
  {
    name: "Brown Rice",
    category: "grains",
    price: 4.99,
    Weight: 5,
    Color: "#8B4513",
    C02: 5,
    Calories: 216,
    imgurl: "./img/Grain/Brown Rice.png",
  },
  {
    name: "Barley",
    category: "grains",
    price: 3.49,
    Weight: 3,
    Color: "#CD853F",
    C02: 3,
    Calories: 123,
    imgurl: "./img/Grain/barley.png",
  },
  {
    name: "Steel-Cut Oats",
    category: "grains",
    price: 6.99,
    Weight: 4,
    Color: "#E6E6FA",
    C02: 4,
    Calories: 170,
    imgurl: "./img/Grain/oats.png",
  },
  {
    name: "Buckwheat",
    category: "grains",
    price: 2.99,
    Weight: 2.5,
    Color: "#FFE4C4",
    C02: 2,
    Calories: 155,
    imgurl: "./img/Grain/wheat.png",
  },
  {
    name: "Organic Blueberries",
    category: "fruits",
    price: 5.99,
    Weight: 1,
    Color: "#4169E1",
    C02: 1,
    Calories: 84,
    imgurl: "./img/Fruits/Organic Blueberries.png",
  },
  {
    name: "Red Grapes",
    category: "fruits",
    price: 3.49,
    Weight: 1.5,
    Color: "#8B0000",
    C02: 2,
    Calories: 90,
    imgurl: "./img/Fruits/red grapes.png",
  },
  {
    name: "Honeycrisp Apples",
    category: "fruits",
    price: 1.99,
    Weight: 0.75,
    Color: "#FFA07A",
    C02: 1,
    Calories: 95,
    imgurl: "./img/Fruits/Honeycrisp Apples.png",
  },
  {
    name: "Bananas",
    category: "fruits",
    price: 0.79,
    Weight: 0.25,
    Color: "#FFD700",
    C02: 1,
    Calories: 105,
    imgurl: "./img/Fruits/Bananas.png",
  },
  {
    name: "Mangoes",
    category: "fruits",
    price: 2.99,
    Weight: 0.5,
    Color: "#FF8C00",
    C02: 2,
    Calories: 135,
    imgurl: "./img/Fruits/Mangoes.png",
  },
  {
    name: "Organic Baby Spinach",
    category: "vegetables",
    price: 3.99,
    Weight: 0.5,
    Color: "#228B22",
    C02: 0.5,
    Calories: 10,
    imgurl: "./img/Vegetables/Organic Baby Spinach.png",
  },
  {
    name: "Carrots",
    category: "vegetables",
    price: 1.49,
    Weight: 1,
    Color: "#FFA500",
    C02: 1,
    Calories: 52,
    imgurl: "./img/Vegetables/Carrots.png",
  },
  {
    name: "Sweet Potatoes",
    category: "vegetables",
    price: 2.99,
    Weight: 2,
    Color: "#FFDAB9",
    C02: 2,
    Calories: 180,
    imgurl: "./img/Vegetables/Sweet Potatoes.png",
  },
  {
    name: "Broccoli",
    category: "vegetables",
    price: 2.29,
    Weight: 0.75,
    Color: "#00FF7F",
    C02: 1,
    Calories: 50,
    imgurl: "./img/Vegetables/Broccoli.png",
  },
  {
    name: "Bell Peppers",
    category: "vegetables",
    price: 1.99,
    Weight: 0.5,
    Color: "#FF69B4",
    C02: 1,
    Calories: 15,
    imgurl: "./img/Vegetables/Bell Peppers.png",
  },
  {
    name: "Organic Tofu",
    category: "protein",
    price: 2.99,
    Weight: 1,
    Color: "#FFC0CB",
    C02: 0.5,
    Calories: 94,
    imgurl: "./img/Protein/Black Beans.png",
  },
  {
    name: "Boneless Skinless Chicken Breast",
    category: "protein",
    price: 4.99,
    Weight: 1.5,
    Color: "#FF4500",
    C02: 3,
    Calories: 150,
    imgurl: "./img/Protein/Chicken Breast.png",
  },
  {
    name: "Salmon Fillets",
    category: "protein",
    price: 10.99,
    Weight: 0.75,
    Color: "#ADD8E6",
    C02: 2,
    Calories: 200,
    imgurl: "./img/Protein/Salmon Fillets.png",
  },
  {
    name: "Black Beans",
    category: "protein",
    price: 1.99,
    Weight: 1,
    Color: "#000000",
    C02: 0.5,
    Calories: 227,
    imgurl: "./img/Protein/Black Beans.png",
  },
  {
    name: "Extra Firm Tempeh",
    category: "protein",
    price: 3.49,
    Weight: 0.5,
    Color: "#8B008B",
    C02: 1,
    Calories: 160,
    imgurl: "./img/Protein/Firm Tempeh.png",
  },
  {
    name: "Organic Whole Milk",
    category: "dairy",
    price: 4.99,
    Weight: 1,
    Color: "#FFFFFF",
    C02: 2,
    Calories: 150,
    imgurl: "./img/Dairy/Whole Milk.png",
  },
  {
    name: "Sharp Cheddar Cheese",
    category: "dairy",
    price: 3.99,
    Weight: 0.5,
    Color: "#FFD700",
    C02: 1,
    Calories: 228,
    imgurl: "./img/Dairy/Cheddar Cheese.png",
  },
  {
    name: "Plain Greek Yogurt",
    category: "dairy",
    price: 2.99,
    Weight: 0.75,
    Color: "#87CEFA",
    C02: 0.5,
    Calories: 100,
    imgurl: "./img/Dairy/Greek Yogurt.png",
  },
  {
    name: "Unsalted Butter",
    category: "dairy",
    price: 3.49,
    Weight: 1,
    Color: "#FFE4B5",
    C02: 1,
    Calories: 102,
    imgurl: "./img/Dairy/Unsalted Butter.png",
  },
  {
    name: "Heavy Whipping Cream",
    category: "dairy",
    price: 2.49,
    Weight: 0.5,
    Color: "#FF69B4",
    C02: 2,
    Calories: 200,
    imgurl: "./img/Dairy/Whipping Cream.png",
  },
];

// hide items on first load
const hideItems = document.querySelector(".items");
hideItems.classList.add("hidden");

const itemList = document.getElementById("item-list");
items.forEach((item) => {
  const container = document.createElement("div");
  container.className = "grid-item";

  const img = document.createElement("img");
  img.src = item.imgurl;
  img.alt = item.name;
  img.width = 200;
  img.height = 150;
  container.appendChild(img);

  const caption = document.createElement("div");
  caption.className = "caption";
  caption.innerText = "Price: $" + item.price.toFixed(2);
  container.appendChild(caption);

  itemList.appendChild(container);
});
